import logging
from pathlib import Path
from config.settings import (
    S3_BUCKET, TRAIN_KEY, REAL_DATA_KEY, INFERENCE_KEY,
    COLUMNS_KEY, MODEL_KEY, TRAIN_RAW_FILE, REAL_DATA,
    INFERENCE_RAW_FILE, COLUMNS_FILE, BEST_MODEL_FILE, AUDITED_KEY, AUDITED_FILE
)
from pipeline.utils import s3_conection

logger = logging.getLogger(__name__)
hook = s3_conection()


def load_training_data():
    """Downloads the raw training dataset from S3 if not already present locally."""
    Path(TRAIN_RAW_FILE).parent.mkdir(parents=True, exist_ok=True)
    if Path(TRAIN_RAW_FILE).exists() and Path(TRAIN_RAW_FILE).stat().st_size > 0:
        logger.info("\033[1;33m[LOAD] Local training dataset already exists. Skipping download.\033[0m")
        return TRAIN_RAW_FILE
    logger.info("\033[1;34m[LOAD] Downloading original training dataset from S3...\033[0m")
    hook.download_file(
        bucket_name=S3_BUCKET,
        key=TRAIN_KEY,
        local_path=str(Path(TRAIN_RAW_FILE).parent),
        preserve_file_name=True,
        use_autogenerated_subdir=False
    )
    logger.info("\033[1;32m[SUCCESS] Training dataset successfully downloaded.\033[0m")
    return TRAIN_RAW_FILE


def load_real_data():
    """Downloads the validation dataset (real data) from S3 and returns its local file path."""
    real_data_path = Path(REAL_DATA)
    real_data_path.parent.mkdir(parents=True, exist_ok=True)
    if real_data_path.exists() and real_data_path.stat().st_size > 0:
        logger.info("\033[1;33m[LOAD] Local validation dataset already exists. Skipping download.\033[0m")
        return real_data_path
    logger.info("\033[1;34m[LOAD] Downloading validation dataset from S3...\033[0m")
    hook.download_file(
        bucket_name=S3_BUCKET,
        key=REAL_DATA_KEY,
        local_path=str(real_data_path.parent),
        preserve_file_name=True,
        use_autogenerated_subdir=False
    )
    logger.info("\033[1;32m[SUCCESS] Validation dataset successfully downloaded.\033[0m")
    return real_data_path


def inference_load():
    """Downloads the unlabelled dataset for inference from S3."""
    Path(INFERENCE_RAW_FILE).parent.mkdir(parents=True, exist_ok=True)
    logger.info("\033[1;34m[LOAD] Downloading inference dataset from S3...\033[0m")
    hook.download_file(
        bucket_name=S3_BUCKET,
        key=INFERENCE_KEY,
        local_path=str(Path(INFERENCE_RAW_FILE).parent),
        preserve_file_name=True,
        use_autogenerated_subdir=False
    )
    logger.info("\033[1;32m[SUCCESS] Inference dataset successfully downloaded.\033[0m")


def load_columns():
    """Downloads the features schema file (columns.pkl) from S3."""
    Path(COLUMNS_FILE).parent.mkdir(parents=True, exist_ok=True)
    logger.info("\033[1;34m[LOAD] Downloading model columns file from S3...\033[0m")
    hook.download_file(
        bucket_name=S3_BUCKET,
        key=COLUMNS_KEY,
        local_path=str(Path(COLUMNS_FILE).parent),
        preserve_file_name=True,
        use_autogenerated_subdir=False
    )
    logger.info("\033[1;32m[SUCCESS] Columns file (columns.pkl) successfully downloaded.\033[0m")


def load_model():
    """Downloads the registered production model artifact from S3."""
    Path(BEST_MODEL_FILE).parent.mkdir(parents=True, exist_ok=True)
    logger.info("\033[1;34m[LOAD] Downloading registered model from S3...\033[0m")
    hook.download_file(
        bucket_name=S3_BUCKET,
        key=MODEL_KEY,
        local_path=str(Path(BEST_MODEL_FILE).parent),
        preserve_file_name=True,
        use_autogenerated_subdir=False
    )
    logger.info("\033[1;32m[SUCCESS] Model successfully downloaded.\033[0m")


def load_audited_data():
    """Downloads the audited production dataset from S3 for monitoring and retraining."""
    local_file = Path(AUDITED_FILE)
    local_file.parent.mkdir(parents=True, exist_ok=True)
    if local_file.exists():
        logger.info("\033[1;33m[CLEANUP] Removing existing file %s to prevent S3Hook locks.\033[0m", local_file.name)
        local_file.unlink()
    logger.info("\033[1;34m[LOAD] Downloading audited file from S3...\033[0m")
    hook.download_file(
        bucket_name=S3_BUCKET,
        key=AUDITED_KEY,
        local_path=str(local_file.parent),
        preserve_file_name=True,
        use_autogenerated_subdir=False
    )
    logger.info("\033[1;32m[SUCCESS] Audited file successfully downloaded.\033[0m")
    return AUDITED_FILE