import os
from datetime import datetime
from pathlib import Path

# ==============================================================================
# 1. BASE & LOCAL DIRECTORIES ⚙️ [KEEP AS DEFAULT]
# ==============================================================================
BASE_DIR = Path("/opt/projects/churn")
DATA_DIR = BASE_DIR / "data"
TARGET_PATH = DATA_DIR / "processed"
MODEL_DIR = DATA_DIR / "models"
INFERENCE_DIR = DATA_DIR / "inference"
INFERENCE_OUTPUT_DIR = DATA_DIR / "inference_outputs"
AUDITED_DIR = DATA_DIR / "audited"

# ==============================================================================
# 2. FILENAMES ⚠️ [MODIFY FOR NEW DATASET]
# ==============================================================================
TRAIN_RAW_FILENAME = 'train.csv'
REAL_DATA_FILENAME = 'churn.csv'       # <- Change to the new validation CSV name (e.g., 'Churn.csv')
INFERENCE_INPUT_FILENAME = 'inference.csv'  # <- Change to the new inference CSV name

PREPROCESSED_FILENAME = 'preprocessed.csv'
TRAIN_SPLIT_FILENAME = 'train_split.csv'
TEST_FILENAME = 'test.csv'
COLUMNS_FILENAME = 'columns.pkl'
MODEL_FILENAME = 'model.pkl'
AUDITED_FILENAME = 'audited.csv'

MODEL_NAME_PATTERN = "model_{model_name}.pkl"
INFERENCE_OUTPUT_PATTERN = "INFERENCE_FILE_{inference_date}.csv"

# ==============================================================================
# 3. LOCAL FILE PATHS ⚙️ [KEEP AS DEFAULT]
# ==============================================================================
TRAIN_RAW_FILE = DATA_DIR / "train" / TRAIN_RAW_FILENAME
TRAIN_SPLIT_FILE = DATA_DIR / "train" / TRAIN_SPLIT_FILENAME
TEST_FILE = DATA_DIR / "test" / TEST_FILENAME
REAL_DATA = DATA_DIR / "real_data" / REAL_DATA_FILENAME
AUDITED_FILE = AUDITED_DIR / AUDITED_FILENAME
TRAIN_PREPROCESSED_FILE = DATA_DIR / "processed" / PREPROCESSED_FILENAME

INFERENCE_RAW_FILE = DATA_DIR / "inference" / INFERENCE_INPUT_FILENAME
COLUMNS_FILE = MODEL_DIR / COLUMNS_FILENAME
BEST_MODEL_FILE = MODEL_DIR / MODEL_FILENAME

# ==============================================================================
# 4. AWS S3 CONFIGURATIONS 🌐 [MODIFY FOR NEW INFRASTRUCTURE]
# ==============================================================================
S3_BUCKET = os.getenv('AWS_S3_BUCKET', 'antonimus-bucket')  # <- Change to the new S3 Bucket
AWS_CONN_ID = 'aws_default'                                 # <- AWS Connection ID in Airflow
S3_PROJECT_PREFIX = 'churn-ml'                            # <- Project prefix/folder in S3

PRESERVE_FILE_NAME = True
USE_AUTOGENERATED_SUBDIR = False
S3_REPLACE = True

TRAIN_KEY = f'{S3_PROJECT_PREFIX}/train/{TRAIN_RAW_FILENAME}'
REAL_DATA_KEY = f'{S3_PROJECT_PREFIX}/real_data/{REAL_DATA_FILENAME}'
INFERENCE_KEY = f'{S3_PROJECT_PREFIX}/inference_data/{INFERENCE_INPUT_FILENAME}'
MODEL_KEY = f'{S3_PROJECT_PREFIX}/model/{MODEL_FILENAME}'
REGISTRY_KEY = f'{S3_PROJECT_PREFIX}/model/{MODEL_FILENAME}'
COLUMNS_KEY = f'{S3_PROJECT_PREFIX}/model/{COLUMNS_FILENAME}'
COLUMNS_REGISTRY_KEY = f'{S3_PROJECT_PREFIX}/model/{COLUMNS_FILENAME}'
OUTPUT_KEY = f'{S3_PROJECT_PREFIX}/output'
S3_OUTPUT_PREFIX = f'{S3_PROJECT_PREFIX}/output/'
AUDITED_KEY = f'{S3_PROJECT_PREFIX}/audited_data/{AUDITED_FILENAME}'

# ==============================================================================
# 5. DATABASE CONFIGURATION (POSTGRES) 🌐 [MODIFY FOR NEW INFRASTRUCTURE]
# ==============================================================================
CONN = 'postgres_default'      # <- Postgres Connection ID in Airflow
TABLE_NAME = 'churn_metrics'         # <- Table name for storing metrics
DB_COLUMNS = ['model_name', 'training_date', 'accuracy', 'roc_auc']

# ==============================================================================
# 6. MACHINE LEARNING (FEATURES, TARGET & MODELS) ⚠️ [MODIFY FOR NEW DATASET]
# ==============================================================================
# Replace all features below with the columns from your new dataset
FEATURES = [
    'tenure','MonthlyCharges', 'TotalCharges','SeniorCitizen','gender',
    'Partner', 'Dependents', 'PhoneService', 'PaperlessBilling','MultipleLines',
    'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
    'StreamingTV', 'StreamingMovies', 'Contract', 'PaymentMethod'
]

# Specify which features are categorical and require encoding
ENCODED_FEATURES = [
    'gender', 'Partner',
    'Dependents', 'PhoneService', 'PaperlessBilling','MultipleLines',
    'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
    'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaymentMethod'
]

TARGET = 'Churn'            # <- Change to the new target column (e.g., 'Churn')
PRED_FEATURES = 'Churn_predicted'

# Hyperparameters and Data Split
TEST_SIZE = 0.3
RANDOM_STATE = 125
RF_RANDOM_STATE = 125
MODEL_LIST = ['logreg', 'rndforest', 'bayes']

# Model Selection Criteria and Threshold for Retraining
WEIGHT_ACCURACY = 0.5
WEIGHT_ROC_AUC = 0.5
SELECTION_METRIC = "roc_auc"
ACCURACY_THRESHOLD = 0.75        # <- Change to the desired business threshold

# Model Specific Parameters
FILL_VALUE_INFERENCE = 0
LOGREG_PARAMS = {"max_iter": 1000, "random_state": 125}
RF_PARAMS = {"n_estimators": 100, "random_state": RF_RANDOM_STATE}
NB_PARAMS = {}

# ==============================================================================
# 7. DATE FORMATTING ⚙️ [KEEP AS DEFAULT]
# ==============================================================================
DATE_FORMAT = "%Y-%m-%d %H:%M:%S%z"
INFERENCE_DATE_FORMAT = "%Y-%m-%d"

# ==============================================================================
# 8. DAG CONFIGURATIONS (AIRFLOW) ⚙️ [KEEP AS DEFAULT]
# ==============================================================================
# Training / Retraining DAG
DAG_ID = "churn_train_dag"
DAG_SCHEDULE = None
DAG_START_DATE = datetime(2020, 1, 1)
DAG_CATCHUP = False
TASK_RETRAIN_ID = "expand_and_train_pipeline"
TASK_SKIP_ID = "skip_retrain"
TRIGGER_RULE_REGISTRY = "none_failed_min_one_success"

# Inference DAG
INFERENCE_DAG_ID = "churn_inference_dag"
INFERENCE_DAG_START_DATE = datetime(2021, 1, 1)
INFERENCE_DAG_SCHEDULE = None
INFERENCE_DAG_CATCHUP = False